2014-03-28 00:30:38,211 - __main__ - ERROR - 404: Not Found
Traceback (most recent call last):
  File "/Users/priyer/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/priyer/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/priyer/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
